worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name _;

        # Твой PWA лежит в /usr/share/nginx/html (куда скопирован public/)
        root /usr/share/nginx/html;
        index index.html;

        

        # SPA‑роутинг: все пути без файлов → index.html
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}